# Generated by Django 2.0.4 on 2018-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnail/%Y/%m/%d/', verbose_name='サムネイル'),
        ),
    ]
